courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about', AboutView.as_view(), name='about'),
    path('contact', ContactView.as_view(), name='contact'),
    path('category/<slug:slug>', CategoryView.as_view(), name='category_detail'),
    path('chapter/<slug:slug>', ChapterDetailView.as_view(), name='chapter_detail'),
    path('course', CourseListView.as_view(), name='course'),
    path('course/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('lesson/<chapter_slug>/<lesson_slug>', LessonDetailView.as_view(), name='lesson_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('create/class/', CreateChapterView.as_view(), name='create_chapter'),
    path('create/course/', CreateCourseView.as_view(), name='create_course'),
    path('create/lesson/', CreateLessonView.as_view(), name='create_lesson'),
]

dandemy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('courses.urls', namespace='courses')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path('', include('memberships.urls', namespace='memberships')),
    # path('', include('blog.urls', namespace='blog')),
    # path('', include('users.urls', namespace='users')),


]

templates/course/chapter_detail.html
{% for co in  course %}
  <h4>
      {{co.title}}
        <a href="{% url 'courses:course_detail' co.slug %}">see more</a>
  </h4>
    <a href="{% url 'courses:lesson_detail' co.slug %}">see more</a>
{% endfor %}

templates/course/course_detail.html
{% for less in chapter %}
<h3>
    {{less.title}}
    {{less.position}}
</h3>
  <a href="{% url 'courses:lesson_detail' less.course.slug less.slug %}">see more</a>
{% endfor %}

templates/course/course_list.html
{% for course in courses %}
  <h3>
      {{ course.title}}
  </h3>
{% endfor %}

templates/course/lesson_detail.html
<h3>
    {{lesson}}
</h3>