courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about', AboutView.as_view(), name='about'),
    path('contact', ContactView.as_view(), name='contact'),
    path('category/<slug:slug>', CategoryView.as_view(), name='category_detail'),
    path('chapter/<slug:slug>', ChapterDetailView.as_view(), name='chapter_detail'),
    path('course', CourseListView.as_view(), name='course'),
    path('course/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('lesson/<chapter_slug>/<lesson_slug>', LessonDetailView.as_view(), name='lesson_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('create/class/', CreateChapterView.as_view(), name='create_chapter'),
    path('create/course/', CreateCourseView.as_view(), name='create_course'),
    path('create/lesson/', CreateLessonView.as_view(), name='create_lesson'),
]

dandemy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('courses.urls', namespace='courses')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path('', include('memberships.urls', namespace='memberships')),
    # path('', include('blog.urls', namespace='blog')),
    # path('', include('users.urls', namespace='users')),


]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <!-- <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
    rel="stylesheet"
    /> -->
    <title>
        {% block title %}
          
        {% endblock title %}
    </title>
</head>
<body>
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Fixed navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Course</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<main class='container'>
    {% block content %}
      
    {% endblock content %}
</main>


    <!-- bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <!-- MDB -->
    <!-- <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script> -->
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
{% for cat in all_categories  %}
<h3>
    {{cat}}
</h3>
  
{% endfor %}

{% for cl in course %}
  <h3> {{cl.title}} </h3>
  <a href="{% url 'courses:course_detail' cl.slug %}">see more</a>
{% endfor %}

<a href="{% url 'courses:course'%}">see all</a>  
{% endblock content %}